video/models.py
from django.db import models

from video.validators import validate_poster_extension, validate_video_extension


class video(models.Model):
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Date added')
    name = models.CharField(max_length=200)
    date_shot = models.DateField(verbose_name='Date taken')
    poster = models.FileField(upload_to='poster/%Y/%m/', validators=[validate_poster_extension])
    video_file = models.FileField(upload_to='video/%Y/%m/', validators=[validate_video_extension])
    description = models.TextField(default=None, blank=True, null=True)
    tags = models.ManyToManyField('tag', default=None, blank=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    lon = models.DecimalField(max_digits=9, decimal_places=6, default=0)

    # Videos are ordered in descending order by the date they were taken. (newest to oldest)
    class Meta:
        ordering = ['-date_shot']

    def __str__(self):
        return '%s, taken on %s' % (self.name, self.date_shot)

    def get_cname(self):
        return self.__class__.__name__

    def get_tags(self):
        return "\n".join([p.name for p in self.tags.all()])


class external_video(models.Model):
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Date added')
    name = models.CharField(max_length=200)
    date_shot = models.DateField(verbose_name='Date taken')
    embed_code = models.TextField(default=None, blank=True, null=True)
    poster = models.FileField(upload_to='poster/%Y/%m/')
    description = models.TextField(default=None, blank=True, null=True)
    tags = models.ManyToManyField('tag', default=None, blank=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    lon = models.DecimalField(max_digits=9, decimal_places=6, default=0)

    # Videos are ordered in descending order by the date they were taken. (newest to oldest)
    class Meta:
        ordering = ['-date_shot']

    def __str__(self):
        return '%s, taken on %s' % (self.name, self.date_shot)

    def get_cname(self):
        return self.__class__.__name__

    def get_tags(self):
        return "\n".join([p.name for p in self.tags.all()])


class album(models.Model):
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Date added')
    name = models.CharField(max_length=200, unique=True)
    videos = models.ManyToManyField('video', default=None, blank=True)
    external_videos = models.ManyToManyField('external_video', default=None, blank=True)
    description = models.TextField(default=None, blank=True, null=True)
    poster = models.FileField(upload_to='poster/%Y/%m/')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return '%s' % self.name


class tag(models.Model):
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Date added')
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return '%s' % self.name


class location(models.Model):
    name = models.CharField(max_length=200, unique=True)
    label = models.CharField(max_length=50, unique=True)
    htmlid = models.CharField(max_length=20, unique=False, verbose_name='HTML id')
    lat = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    lon = models.DecimalField(max_digits=9, decimal_places=6, default=0)

    def __str__(self):
        return '%s' % self.name

video/templates/base-admin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	{% load static %}
	<link rel="shortcut icon" type="image/png" href="{% static "img/video-camera.png" %}">

	<title>Leo and Jen Video Site</title>

	<!-- Bootstrap core CSS -->
	<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="{% static "css/video-custom.css" %}" rel="stylesheet">

	<!--JQuery -->
	<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
</head>
<body>

  {% block content %}{% endblock %}

	<!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{% static "js/1.11.3/jquery.min.js" %}"></script>
	<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/docs.min.js" %}"></script>

</body>
</html>

video/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		{% load static %}
		<link rel="shortcut icon" type="image/png" href="{% static "img/video-camera.png" %}">

		<title>Leo and Jen - The Video Gallery</title>

		<!-- Bootstrap core CSS -->
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

		<!-- Custom styles for this template -->
		<link href="{% static "css/video-custom.css" %}" rel="stylesheet">

		<!-- Video.js and plugins -->
		<link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />

		<!-- JQuery custom css -->
		<link href="{% static "js/jquery-ui.min.css" %}" rel="stylesheet">

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
		<script src="{% static "js/bootstrap.min.js" %}"></script>
		<script src="{% static "js/jquery-ui.min.js" %}""></script>

		{% include "leaflet_head.html" %}
	</head>
	<body>

    {% include "nav.html" %}

		<div class="container">

    	{% block content %}{% endblock %}

	    <div class="footer">
	    </div>
  </div> <!-- /container -->
  <script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>
  <script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1980:2022",
    });
  });
  </script>

	{% include "leaflet_foot.html" %}

</body>
</html>

video/templates/edit.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% load widget_tweaks %}

<!-- Start Video Upload section -->
{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

<h2><a href="#video_form_section">Upload a New Video</a></h2>
<div class="row well well-lg" id="video_form_section">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <p><a href="https://www.latlong.net/" target="_blank">Latitude/Longtiude Help</a></p>
        <form class="form-horizontal" action="{% if from %}?next={{ from }}{% endif %}" method="post" enctype="multipart/form-data">
            <div class="well">
                {% csrf_token %}
                {%if edit_form.non_field_errors%}
                <div class="alert alert-danger" role="alert">
                    {{ edit_form.non_field_errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    {%if edit_form.tags.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ edit_form.tags.errors }}
                    </div>
                    {% endif %}
                    <div class="fieldWrapper">
                        {{ edit_form.tags.errors }}
                        <label class="col-sm-2 control-label" for="{{ edit_form.tags.id_for_label }}">Tags</label>
                        <div class="col-sm-6">
                            {{ edit_form.tags|add_class:"form-control multi-selects" }}
                        </div>
                    </div>
                    <a href="#"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                </div>
                <div class="form-group">
                    {%if edit_form.name.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ edit_form.name.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ edit_form.name.id_for_label }}">Name</label>
                    <div class="col-sm-6">
                        {{ edit_form.name|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    {%if edit_form.date_shot.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ edit_form.date_shot.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ edit_form.date_shot.id_for_label }}">Date
                        Taken</label>
                    <div class="col-sm-6">
                        {{ edit_form.date_shot }}
                    </div>
                </div>
                <div class="form-group">
                    {%if edit_form.description.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ edit_form.description.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ edit_form.description.id_for_label }}">Description</label>
                    <div class="col-sm-6">
                        {{ edit_form.description|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    {%if edit_form.lat.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ edit_form.lat.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ edit_form.lat.id_for_label }}">Latitude</label>
                    <div class="col-sm-6">
                        {{ edit_form.lat }}
                    </div>
                </div>
                <div class="form-group">
                    {%if edit_form.lon.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ edit_form.lon.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ edit_form.lon.id_for_label }}">Longitude</label>
                    <div class="col-sm-6">
                        {{ edit_form.lon }}
                    </div>
                </div>
                <div class="row" id="qloc-row">
                {%for qloc in quick_locations%}
                    <button type="button" id="{{qloc.htmlid}}" class="btn btn-default">{{qloc.label}}</button>
                {%endfor%}
                </div>
                <div class="form-group">
                    {%if edit_form.poster.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ edit_form.poster.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ edit_form.poster.id_for_label }}">Poster</label>
                    <div class="col-sm-6">
                        {{ edit_form.poster }}
                    </div>
                </div>
            </div>
            <input class="btn btn-primary btn-lg" type="submit" name="save_shot"
                   value="Save"/>
            <input class="btn btn-primary btn-lg" type="submit" name="save_video_and_main"
                   value="Save and Back to Main"/>
            <button type="submit" class="btn btn-lg btn-default" name="cancel-button">Cancel</button>
        </form>
    </div>
</div>

<!-- End shot edit form -->

<script>
$(document).ready(function(){
{%for qloc in quick_locations%}
        $("#{{qloc.htmlid}}").click(function() {
          $("#id_lon").val({{qloc.lon}});
          $("#id_lat").val({{qloc.lat}});
        });
{%endfor%}
{%for qloc in quick_locations%}
        $("#{{qloc.htmlid}}_vr").click(function() {
          $("#id_lon_vr").val({{qloc.lon}});
          $("#id_lat_vr").val({{qloc.lat}});
        });
{%endfor%}
});
</script>

{%endblock content%}

video/templates/index.html
{% extends "base.html" %}

  {% block content %}
  {% load static %}

  <div class="row well well-lg">
    {% if messages %}
    <div class="alert alert-success" role="alert">
          {% for message in messages %}
          <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
          {% endfor %}
    </div>
    {% endif %}
    <div class="col-sm-6 col-xs-12">
      <h2>Video Tags</h2>
      {%for tag in tag_list%}
        <a class="btn btn-primary btn-lg btn-margin" href="/tag/{{tag.name}}" role="button">{{tag.name}}</a>
      {%endfor%}
    </div>
    <div class="col-sm-6 col-xs-12">
      <h2>Newly added</h2><p class="text-right"><span class="label label-info">Sorted by Most Recently shot.</span></p>
        {%for shot in most_recent%}
          {%if shot.get_cname == "video"%}
            <a href="/recent/video/{{shot.id}}">
              <img class="album-poster-recent" src="{{ MEDIA_URL }}{{shot.poster}}">
            </a>
          {%elif shot.get_cname == "external_video"%}
            <a href="/recent/external/{{shot.id}}">
              <img class="album-poster-recent" src="{{ MEDIA_URL }}{{shot.poster}}">
            </a>
          {%endif%}
        {%endfor%}
    </div>
  </div>

  <h2>Current Video Albums</h2>
	{%for album in albums%}
  <div class="row well well-lg">
		<div class="col-md-4 col-sm-4 col-xs-12">
      <a href="/album/{{album.id}}"><img src="{{ MEDIA_URL }}/{{album.poster}}" class="img-responsive center-block" /></a>
    </div>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <a href="/album/{{album.id}}"><h2>{{album.name}}</h2></a>
      {% autoescape off %}
      <p>{{album.description}}</p>
      {%endautoescape%}
    </div>
  </div>
  {%empty%}
  	<p>No albums created.</p>
  {%endfor%}

{%endblock content%}

video/templates/leaflet_foot.html
<!-- Javascript for leaflet map -->
    {% load static %}

    <script type="text/javascript">
        var video_map_data = {{video_map_data|safe}}
        var external_map_data = {{external_map_data|safe}}
    </script>
    <script src="{% static "js/leaflet_map_custom.js"%}"></script>

video/templates/leaflet_head.html
<!-- Leaflet and map items -->
        {% load static %}
        <link rel="stylesheet" href="{% static "leaflet/leaflet.css"%}" />
        <script src="{% static "leaflet/leaflet.js"%}"></script>
        <link rel="stylesheet" href="{% static "markercluster/MarkerCluster.css"%}" />
        <link rel="stylesheet" href="{% static "markercluster/MarkerCluster.Default.css"%}" />
        <script src="{% static "markercluster/leaflet.markercluster.js"%}"></script>
        <!-- end Leaflet/map -->

video/templates/login.html
{% extends "base-admin.html" %}

{% block navbar %}{% endblock %}

{% block content %}

<div class="login-wrapper">
  {%if next%}
  <form action="/?next={{next}}" class="form-signin" method="post" >
  {%else%}
  <form action="/" class="form-signin" method="post">
  {%endif%}
    {% csrf_token %}
    <h2 class="form-signin-heading">{{message}}</h2>
    <input type="text" class="form-control" name="username" placeholder="Username" required="" autofocus="" />
    <input type="password" class="form-control" name="password" placeholder="Password" required=""/>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
  </form>
</div>

{%endblock content%}

video/templates/map_shot.html
{% extends "base.html" %}

  {% block content %}
  {% load static %}

  <ol class="breadcrumb">
    {%if album_view%}
      <li>Album</li>
      <li><a href="/album/{{album.id}}">{{album.name}}</a></li>
    {%elif tag_view%}
      <li>Tag</li>
      <li><a href="/tag/{{the_tag.name}}">{{the_tag.name}}</a></li>
    {%elif recent_view%}
      <li>Recent</li>
    {%endif%}
    <li class="active">{{video.name}}</li>
  </ol>

  <div class="row">
    <div class="row well well-lg">
      <div class="col-md-6 col-sm-8 col-xs-12">
        {%if video.get_cname == "video"%}
        <!-- Start HTML5 video player -->
        <div class="embed-responsive embed-responsive-16by9">
          <video id="my-video" class="video-js embed-responsive-item" controls preload="auto" width="640" height="264"
          poster="{{ MEDIA_URL }}/{{video.poster}}" data-setup="{}">
            <source src="{{ MEDIA_URL }}{{video.video_file}}" type='video/mp4'>
            <p class="vjs-no-js">
              To view this video please enable JavaScript, and consider upgrading to a web browser that
              <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
            </p>
          </video>
        </div>
        <!-- End HTML5 Video player -->
        {%elif video.get_cname == "external_video"%}
        <!-- put embed code here -->
          {% autoescape off %}
            {{video.embed_code}}
          {% endautoescape %}
        <!-- end embed code -->
        {%endif%}
      </div>
      <div class="col-md-6 col-sm-4 col-xs-12">
        <h3>{{video.name}}</h3>
        {% autoescape off %}
        {%if user.is_staff == True%}
          {%if video.get_cname == "video"%}
            <a href="/edit/video/{{video.id}}">Edit</a>
          {%endif%}
        {%endif%}
        <p>{{video.description}}</p>
        {%endautoescape%}
        <p>Date Taken: <strong>{{video.date_shot}}</strong></p>
        <strong>Tags</strong>
        <p>
        {%for tag in video_tags%}
          <a class="btn btn-default" href="/tag/{{tag.name}}" role="button">{{tag.name}}</a>
        {%endfor%}
        </p>
        <p><strong>Navigate</strong><p>
          <div id="map" class="map_embed"></div>
            <script type="text/javascript">
                var customLat = {{video.lat}}
                var customLon = {{video.lon}}
            </script>

      </div>
    </div>
  </div>

{%endblock content%}

video/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/main/">Leo and Jen - Video Gallery</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active">
            	<a href="/main/">Home</a>
            </li>
		    <li>
			  <a href="/random/">Random Video</a>
		    </li>
		    <li>
			  <a href="/map/">Map</a>
		    </li>
			{%if user.is_staff == True%}
				<li id="upload"><a href="/main/upload/">Upload/Create</a></li>
			{%endif%}
			<li><a href="/logout/">Logout</a></li>
          </ul>
		  <div id="login-as">
			<p class="text-right">Logged in as <strong>{{user.username}}</strong></p>
		  </div>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

video/templates/prev_next_shot.html
<div class=row>
  {%if not no_prev%}
  <div class="col-md-6 col-sm-6 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Earlier Video</h3>
      </div>
      <div class="panel-body">
        {%if album_view%}
            {%if prev_video.get_cname == "video"%}
              <a href="/album/{{album.id}}/video/{{prev_video.id}}" class="thumbnail">
            {%elif prev_video.get_cname == "external_video"%}
              <a href="/album/{{album.id}}/external/{{prev_video.id}}" class="thumbnail">
            {%endif%}
        {%elif tag_view%}
            {%if prev_video.get_cname == "video"%}
              <a href="/tag/{{the_tag.name}}/video/{{prev_video.id}}" class="thumbnail">
            {%elif prev_video.get_cname == "external_video"%}
              <a href="/tag/{{the_tag.id}}/external/{{prev_video.id}}" class="thumbnail">
            {%endif%}
        {%elif recent_view%}
            {%if prev_video.get_cname == "video"%}
              <a href="/recent/video/{{prev_video.id}}" class="thumbnail">
            {%elif prev_video.get_cname == "external_video"%}
              <a href="/recent/external/{{prev_video.id}}" class="thumbnail">
            {%endif%}
        {%endif%}
          <img src="{{ MEDIA_URL }}/{{prev_video.poster}}" alt="...">
        </a>
      </div>
    </div>
  </div>
  {%endif%}
  {%if not no_next%}
  <div class="col-md-6 col-sm-6 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Later Video</h3>
      </div>
      <div class="panel-body">
        {%if album_view%}
            {%if next_video.get_cname == "video"%}
              <a href="/album/{{album.id}}/video/{{next_video.id}}" class="thumbnail">
            {%elif next_video.get_cname == "external_video"%}
              <a href="/album/{{album.id}}/external/{{next_video.id}}" class="thumbnail">
            {%endif%}
        {%elif tag_view%}
            {%if next_video.get_cname == "video"%}
              <a href="/tag/{{the_tag.name}}/video/{{next_video.id}}" class="thumbnail">
            {%elif next_video.get_cname == "external_video"%}
              <a href="/tag/{{the_tag.name}}/external/{{next_video.id}}" class="thumbnail">
            {%endif%}
        {%elif recent_view%}
            {%if next_video.get_cname == "video"%}
              <a href="/recent/video/{{next_video.id}}" class="thumbnail">
            {%elif next_video.get_cname == "external_video"%}
              <a href="/recent/external/{{next_video.id}}" class="thumbnail">
            {%endif%}
        {%endif%}
          <img src="{{ MEDIA_URL }}/{{next_video.poster}}" alt="...">
        </a>
      </div>
    </div>
  </div>
  {%endif%}
</div>

video/templates/tag.html
{% extends "base.html" %}

  {% block content %}
  {% load static %}

	<h1>Videos tagged "{{the_tag.name}}"</h1>
  <p class="text-right"><span class="label label-info">Sorted by Most Recent.</span></p>
  <div class="row">
    {%for video in videos_w_tag%}
    <div class="col-sm-6 col-xs-12">
      <div class="well well-lg">
        {%if video.get_cname == "video"%}
          <a href="/tag/{{the_tag.name}}/video/{{video.id}}">
        {%elif video.get_cname == "external_video"%}
          <a href="/tag/{{the_tag.name}}/external/{{video.id}}">
        {%endif%}
          <div class="album-poster" style="background-image:url({{ MEDIA_URL }}/{{video.poster}});"></div>
        </a>
        <h4>{{video.name}}</h4>
        {% autoescape off %}
        <p>{{video.description}}</p>
        <p><strong>Date Taken:</strong> {{video.date_shot}}</p>
        {%endautoescape%}
      </div>
    </div>
  {%if forloop.counter|divisibleby:2%}
  </div>
  <div class="row">
  {%endif%}
  {%endfor%}
  </div>

{%endblock content%}

video/templates/upload.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% load widget_tweaks %}

<!-- Start Video Upload section -->
{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

<h2><a href="#video_form_section" data-toggle="collapse">Upload a New Video</a></h2>
<div class="row well well-lg collapse" id="video_form_section">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <p><a href="https://www.latlong.net/" target="_blank">Latitude/Longtiude Help</a></p>
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            <div class="well">
                {% csrf_token %}
                {%if upload_form.non_field_errors%}
                <div class="alert alert-danger" role="alert">
                    {{ upload_form.non_field_errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    {%if upload_form.tags.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.tags.errors }}
                    </div>
                    {% endif %}
                    <div class="fieldWrapper">
                        {{ upload_form.tags.errors }}
                        <label class="col-sm-2 control-label" for="{{ upload_form.tags.id_for_label }}">Tags</label>
                        <div class="col-sm-6">
                            {{ upload_form.tags|add_class:"form-control multi-selects" }}
                        </div>
                    </div>
                    <a href="#"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                </div>
                <div class="form-group">
                    {%if upload_form.album.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.album.errors }}
                    </div>
                    {% endif %}
                    <div class="fieldWrapper">
                        {{ upload_form.album.errors }}
                        <label class="col-sm-2 control-label" for="{{ upload_form.album.id_for_label }}">Albums</label>
                        <div class="col-sm-6">
                            {{ upload_form.album|add_class:"form-control multi-selects" }}
                        </div>
                    </div>
                    <a href="#"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                </div>
                <div class="form-group">
                    {%if upload_form.name.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.name.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ upload_form.name.id_for_label }}">Name</label>
                    <div class="col-sm-6">
                        {{ upload_form.name|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    {%if upload_form.date_shot.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.date_shot.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ upload_form.date_shot.id_for_label }}">Date
                        Taken</label>
                    <div class="col-sm-6">
                        {{ upload_form.date_shot }}
                    </div>
                </div>
                <div class="form-group">
                    {%if upload_form.description.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.description.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ upload_form.description.id_for_label }}">Description</label>
                    <div class="col-sm-6">
                        {{ upload_form.description|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    {%if upload_form.lat.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.lat.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ upload_form.lat.id_for_label }}">Latitude</label>
                    <div class="col-sm-6">
                        {{ upload_form.lat }}
                    </div>
                </div>
                <div class="form-group">
                    {%if upload_form.lon.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.lon.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ upload_form.lon.id_for_label }}">Longitude</label>
                    <div class="col-sm-6">
                        {{ upload_form.lon }}
                    </div>
                </div>
                <div class="row" id="qloc-row">
                {%for qloc in quick_locations%}
                    <button type="button" id="{{qloc.htmlid}}" class="btn btn-default">{{qloc.label}}</button>
                {%endfor%}
                </div>
                <div class="form-group">
                    {%if upload_form.poster.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.poster.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ upload_form.poster.id_for_label }}">Poster</label>
                    <div class="col-sm-6">
                        {{ upload_form.poster }}
                    </div>
                </div>
                <div class="form-group">
                    {%if upload_form.video_file.errors%}
                    <div class="alert alert-danger" role="alert">
                        {{ upload_form.video_file.errors }}
                    </div>
                    {% endif %}
                    <label class="col-sm-2 control-label" for="{{ upload_form.video_file.id_for_label }}">Video
                        File</label>
                    <div class="col-sm-6">
                        {{ upload_form.video_file }}
                    </div>
                </div>
            </div>
            <input class="btn btn-primary btn-lg" type="submit" name="save_video" value="Save and Add Another"/>
            <input class="btn btn-primary btn-lg" type="submit" name="save_video_and_main"
                   value="Save and Back to Main"/>
        </form>
    </div>
</div>

<!-- End Video Upload section -->

<script>
$(document).ready(function(){
{%for qloc in quick_locations%}
        $("#{{qloc.htmlid}}").click(function() {
          $("#id_lon").val({{qloc.lon}});
          $("#id_lat").val({{qloc.lat}});
        });
{%endfor%}
});
</script>
<script>
    $(document).ready(function () {
    $(".nav li").removeClass("active");
    $('#upload').addClass('active');
});
</script>

{%endblock content%}